### ISSUE TITLE
cant unstall cairocffi1.0.2 while running bin/buildout

### ISSUE THREAD

**Issue by BettyAHRI** [BaobabLims/baobab.lims#107]
Develop distribution: graphite.theme 1.2
uses namespace packages but the distribution does not require setuptools.
Getting distribution for 'cairocffi>=0.4'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 2265, in main
    **kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-emCRIA/cairocffi-1.0.2/setup.py", line 7, in <module>
RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
An error occurred when trying to install cairocffi 1.0.2. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'cairocffi>=0.4'.
Error: Couldn't install: cairocffi 1.0.2

**Comment by hocinebendou** [comment]
@BettyAHRI, add this line to the end of your buildout.cfg:
```
cairocffi = 0.9.0
```
Save the file and run again `bin/buildout`
