### ISSUE TITLE
Issue with Cairocffi

### ISSUE THREAD

**Issue by jsan4christ** [BaobabLims/baobab.lims#109]
Following the installation guide, but failed to move passed that point both for zinstance and zeoserver. Is there anything I need to change? 

Getting distribution for 'cairocffi>=0.4'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 2265, in main
    **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-pe1cYN/cairocffi-1.0.2/setup.py", line 7, in <module>
RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
An error occurred when trying to install cairocffi 1.0.2. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'cairocffi>=0.4'.
Error: Couldn't install: cairocffi 1.0.2

Please advise,

**Comment by Dominique0804** [comment]
Hi there. 

https://github.com/BaobabLims/baobab.lims/issues/107#issuecomment-474398980

Please see link. 
Add the line cairocffi = 0.9.0 to the end of the buildout.cfg

Save the file and run bin/buildout again

**Comment by jsan4christ** [comment]
Excellent, thank you.

That worked.
