### ISSUE TITLE
ERROR Application Could not import Products.AdvancedQuery

### ISSUE THREAD

**Issue by espirado** [BaobabLims/baobab.lims#110]
sudo -u plone_daemon bin/client1 fg
2019-04-23 06:56:51 INFO ZServer HTTP server started at Tue Apr 23 06:56:51 2019
	Hostname: 0.0.0.0
	Port: 8086
2019-04-23 06:56:52 ERROR Application Could not import Products.AdvancedQuery
Traceback (most recent call last):
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/Application.py", line 606, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/__init__.py", line 19, in <module>
    from .eval import eval as _eval, _notPassed
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/__init__.py", line 18, in <module>
    from .interfaces import IQueryContext
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/interfaces.py", line 9, in <module>
    from .transform import IOptimizer, IOrdered, IOptimizerChain, ITransformer
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/transform.py", line 102, in <module>
    from .adapter import getSubscriptionAdapter, querySubscriptionAdapter
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/adapter/__init__.py", line 44, in <module>
    from zope.interface.interfaces import ComponentLookupError
ImportError: cannot import name ComponentLookupError
Traceback (most recent call last):
  File "/usr/local/Plone/zeocluster/parts/client1/bin/interpreter", line 317, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/startup.py", line 67, in startup
    OFS.Application.import_products()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/Application.py", line 583, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/Application.py", line 606, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/__init__.py", line 19, in <module>
    from .eval import eval as _eval, _notPassed
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/__init__.py", line 18, in <module>
    from .interfaces import IQueryContext
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/interfaces.py", line 9, in <module>
    from .transform import IOptimizer, IOrdered, IOptimizerChain, ITransformer
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/transform.py", line 102, in <module>
    from .adapter import getSubscriptionAdapter, querySubscriptionAdapter
  File "/usr/local/Plone/buildout-cache/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/adapter/__init__.py", line 44, in <module>
    from zope.interface.interfaces import ComponentLookupError
ImportError: cannot import name ComponentLookupError

**Comment by Dominique0804** [comment]
The solution is to edit buildout.cfg and:
Add these to [versions] section:

Products.AdvancedQuery = 3.0.4
cairocffi = 0.9.0

**Comment by espirado** [comment]
Hey
 Hope your great been away for sometime. Thanks it worked...
