### ISSUE TITLE
Error Buildout

### ISSUE THREAD

**Issue by patricksl** [BaobabLims/baobab.lims#114]
ubuntu@ubuntu-Virtual-Machine:/usr/local/Plone/zeocluster$ bin/buildout
Develop: '/usr/local/Plone/zeocluster/src/bika.lims'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Develop: '/usr/local/Plone/zeocluster/src/baobab.lims'
Develop: '/usr/local/Plone/zeocluster/src/graphite.theme'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Updating zeoserver.
Installing client1.
/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Develop distribution: graphite.theme 1.2
uses namespace packages but the distribution does not require setuptools.
Getting distribution for 'openpyxl'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 2265, in main
    **kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-NuE_4H/openpyxl-3.0.3/setup.py", line 28, in <module>
ImportError: No module named util
An error occurred when trying to install openpyxl 3.0.3. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'openpyxl'.
Error: Couldn't install: openpyxl 3.0.3
ubuntu@ubuntu-Virtual-Machine:/usr/local/Plone/zeocluster$ dir

**Comment by zipho** [comment]
Hi Patrick

The following merge on bika lims should fixed the openpyxl issue above.

https://github.com/BaobabLims/bika.lims/pull/6

Please run `bin/buildout` again.
