### ISSUE TITLE
cairocffi install issue during build

### ISSUE THREAD

**Issue by jayramr** [BaobabLims/baobab.lims#156]
Hi Team, 

I'm facing issue with the installation on RHEL9 and Ubuntu 20.04 with the same error.

I followed this document -> https://github.com/BaobabLims/baobab.lims/wiki/Baobab-Lims-Manual-Installation-using-Miniconda

buildout.cfg 

```

eggs =
    Plone
    Pillow
    bika.lims
    baobab.lims
    graphite.theme
develop =
    src/bika.lims
    src/baobab.lims
    src/graphite.theme
[versions]
zc.buildout =
setuptools =
Pillow = 5.1.0
cssselect2 = 0.2.2
soupsieve = 1.9.5
xlsxwriter = 2.0.0
werkzeug = 1.0.1
buildout.sanitycheck = 1.0.2
collective.recipe.backup = 4.0
plone.recipe.unifiedinstaller = 4.3.2
Products.DCWorkflow = 2.2.4

```

```
PYTHONHTTPSVERIFY=0 buildout
Develop: '/home/baobab/baobablims/src/bika.lims'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Develop: '/home/baobab/baobablims/src/baobab.lims'
Develop: '/home/baobab/baobablims/src/graphite.theme'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Installing instance.
Getting distribution for 'cairocffi==0.9.0'.
  File "build/bdist.linux-x86_64/egg/cffi/_shimmed_dist_utils.py", line 16
    raise Exception("This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.") from ex
                                                                                                                                       ^
SyntaxError: invalid syntax

  File "/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/_shimmed_dist_utils.py", line 16
    raise Exception("This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.") from ex
                                                                                                                                       ^
SyntaxError: invalid syntax


Installed /tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg
Searching for pycparser
Reading https://pypi.org/simple/pycparser/
Downloading https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl#sha256=8ee45429555515e1f6b185e78100aea234072576aa43ab53aefcae078162fca9
Best match: pycparser 2.21
Processing pycparser-2.21-py2.py3-none-any.whl
Installing pycparser-2.21-py2.py3-none-any.whl to /tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs

Installed /tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/pycparser-2.21-py2.7.egg
/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/cparser.py:154: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
  warnings.warn("String literal found in cdef() or type source. "
/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/cparser.py:165: UserWarning: Global variable 'CAIRO_TAG_DEST' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/cparser.py:165: UserWarning: Global variable 'CAIRO_TAG_LINK' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2312, in main
    **kw
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/baobab/Python-2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/baobab/Python-2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/baobab/Python-2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
    run_setup(setup_script, args)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/baobab/Python-2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/baobab/Python-2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-03fpbN/cairocffi-0.9.0/setup.py", line 51, in <module>
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/baobab/Python-2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/home/baobab/Python-2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 216, in cffi_modules
  File "/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 69, in add_cffi_module
  File "/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 153, in _add_py_module
  File "/tmp/easy_install-03fpbN/cairocffi-0.9.0/.eggs/cffi-1.16.0-py2.7-linux-x86_64.egg/cffi/_shimmed_dist_utils.py", line 16
    raise Exception("This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.") from ex
                                                                                                                                       ^
SyntaxError: invalid syntax
An error occurred when trying to install /home/baobab/buildout-cache/downloads/dist/cairocffi-0.9.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'cairocffi==0.9.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/home/baobab/buildout-cache/eggs/plone.recipe.zope2instance-4.4.1-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 169, in install
    installed.extend(self.install_scripts())
  File "/home/baobab/buildout-cache/eggs/plone.recipe.zope2instance-4.4.1-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 668, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "/home/baobab/buildout-cache/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/egg/egg.py", line 101, in working_set
    **kw)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/baobab/Python-2.7/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
```

Please advise. 

Thanks
Jay

**Comment by jayramr** [comment]
Hi , 

Kindly let me know

**Comment by jayramr** [comment]
I sorted this issue by installation older version of cairocffi

```
pip install cairocffi==0.5.3
pip install Pyphen
pip install importlib-metadata
```
